[tool.poetry]
name = "chatregex"
version = "0.1.0"
description = ""
authors = ["bfinlayson-hbu <bfinlayson@hbu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
